#include "umf/umf_core.lua"
#include "umf/extension/meta/vector.lua"
#include "umf/extension/meta/quat.lua"
#include "umf/extension/meta/transform.lua"
#include "umf/extension/meta/entity.lua"
#include "umf/extension/meta/body.lua"
#include "umf/extension/meta/shape.lua"
#include "umf/extension/meta/location.lua"
#include "umf/extension/meta/joint.lua"
#include "umf/extension/meta/light.lua"
#include "umf/extension/meta/trigger.lua"
#include "umf/extension/meta/screen.lua"
#include "umf/extension/meta/vehicle.lua"
#include "umf/extension/meta/player.lua"
#include "umf/extension/meta/armature.lua"

UpdateQuickloadPatch()